webdevcody/survive-the-night-sim

.env.example
Dockerfile
README.md
next.config.mjs

This is linked to this issue #8 
The main changes here are creating a Dockerfile for the project and updating README to show steps for what variables to set for deployment, there is also the .env.example file as an example.
Please add any comments or suggestions!

feat: Setup Dockerfile and deploy to railway

---

README.md

docs: correct read me typing mistake

---

.gitignore
app/page.tsx
components/MapTester.tsx
convex/_generated/api.d.ts
convex/openai.ts
package.json

add the playermap action, and give out a handle to test out the results after having started out with the init config on the main page

---

.github/actions/setup/action.yml
.github/workflows/convex.yml

Also added composite setup action that can be reused in future workflows if needed for installing node and dependencies
issue: Setup CI/CD Pipeline to Deploy Convex #6

ci: added github action for deploying convex functions

---

.gitignore
convex/_generated/api.d.ts
convex/saveRound.ts
convex/schema.ts

#9 issue worked on to add saveRound.ts and relates schemas to work with

---

README.md

Update the Env Setup section in README.md

---

convex/_generated/api.d.ts
convex/constants.ts
convex/games.ts
convex/gemini.ts
convex/results.ts
package.json

fixes #29
NOTE: Needs error handling for some cases when the simulation is erroring out...

add gemini model for the game simulation

---

app/header.tsx
app/layout.tsx
convex/openai.ts

closes #28 
I've fixed the light mode and added a theme toggle to the header.

Light mode with theme toggle

---

app/header.tsx
app/layout.tsx
convex/openai.ts

Reverts webdevcody/survive-the-night-sim#32

Revert "Light mode with theme toggle"

---

app/globals.css
app/header.tsx
components/ThemeToggle.tsx
tailwind.config.ts

fixes #28
- dark mode:
- light mode:

fix for the light mode

---

app/games/[gameId]/result.tsx
convex/maps.ts
convex/results.ts
convex/schema.ts

Now when something goes off you will see what exactly:
Other than that, I displayed reasoning of AI model:

Proper error handling/Display AI model reasoning

---

models/gemini-1.5-pro.ts
models/gpt-4o.ts
models/index.ts

The idea is to have prompt and checks passed down to models so people adding models don't need to care about this.

Move prompt/checks to models/index.ts

---

app/games/[gameId]/visualizer.tsx
app/header.tsx
app/maps/page.tsx
convex/maps.ts

fixes #24 
- Ability for logged in user to add custom maps
- The maps are added directly to database for all the users to access.

Add Custom Maps

---

app/play/[level]/page.tsx
app/play/page.tsx
components/ui/skeleton.tsx

Improved loading states

---

app/games/[gameId]/visualizer.tsx
app/header.tsx
app/maps/page.tsx
components/ThemeToggle.tsx
convex/maps.ts

fixes #54 
- The app changes theme as the system if system toggle is enabled
- The app also has the ability to override system theme preference

Theme Toggle improved

---

app/games/[gameId]/page.tsx
convex/README.md
models/claude-3-5-sonnet.ts
models/perplexity-llama.ts
package.json

Fixed the claude model error by renaming it as i misspelled the name and perplexity it didnt allow two user based role prompt continuously so i merged them together

Fixed claude and perplexity errors for ai models 

---

app/play/page.tsx

Closes: #77 
If anyone has a more creative idea let me know

style: made it more obvious if you already bet a level

---

app/play/page.tsx

Closes #76 
Additionally, corrected the grammar of the player count that bet a level
https://github.com/user-attachments/assets/4f29e621-f9ed-4bdd-a59e-2489026b111f

feat: added toggles for the night overview

---

app/play/page.tsx
convex/maps.ts
convex/schema.ts
convex/users.ts

index on the admin table and fix some syntax errors on the play page

---

convex/maps.ts
convex/users.ts
package.json

add admin mutation and query helpers

---

app/play/[level]/page.tsx
convex/maps.ts

add the functionality to move to the next map on victory

---

app/page.tsx
app/playground/page.tsx
components/MapBuilder.tsx
components/ThemeToggle.tsx
components/Visualizer.tsx
convex/maps.ts
lib/utils.ts
models/index.ts
simulators/zombie-survival/ZombieSurvival.ts
simulators/zombie-survival/entities/Entity.ts

As part of this PR:
- fixed convex compilation issue
- allow users to edit playground map after playing it
- fix convex last level issue when publishing map
- prevented selecting map builder cells
- persist map between page reloads with localStorage
- improved Watch page layout

Improved Visualizer performance

---

app/header.tsx

feat(frontend): added button to GitHub repo

---

app/prompts/[promptId]/page.tsx
convex/leaderboard.ts
convex/prompts.ts
convex/schema.ts

This pr addresses #104 as well as closing some of the changes requested at the end of this #106

Ranking changes

---

app/header.tsx
app/play/page.tsx
convex/maps.ts

Closes #99 
As part of this PR:
- set logo image priority

Ability to delete maps from Play page

---

app/play/[level]/[attempt]/page.tsx

fix: improved loading on /play/[level]/[attempt] page

---

app/play/page.tsx

fix: removed a false hint on the /play page

---

app/playground/page.tsx
components/ui/dialog.tsx
convex/users.ts
package.json

fix: improved error handling on sign in on /plaground page

---

package.json

fix(deps): SECURITY updated next

---

app/header.tsx
app/settings/page.tsx
convex/users.ts

This pr is for #131.
Let me know if theres any changes wanted. Discord - edinstance

Delete account functionality

---

app/play/[level]/test-mode.tsx
app/playground/page.tsx
convex/maps.ts
hooks/useAITesting.ts
models/claude-3-5-sonnet.ts
models/gemini-1.5-pro.ts
models/gpt-4o.ts
models/index.ts
models/mistral-large-2.ts
models/perplexity-llama-3.1.ts

- Obtain tokens (input, output, total) for a test of a model
- Using Price calculate total cost of running model
- Display all value to user (can be selected to keep ones that are required)

feat(display tokens used and total cost)

---

app/playground/page.tsx
convex/_generated/api.d.ts
convex/_generated/api.js
convex/_generated/server.d.ts
convex/_generated/server.js
convex/convex.config.ts
convex/maps.ts
convex/rateLimits.ts
package.json

This pr is for #118 and it adds a rate limit of 3 submitted maps per minute.

feat: added rate limiting to the submit map mutation

---

app/header.tsx

fix(style): put header on top of cards
